// packages/react/src/components/DiffHtml.tsx
import { forwardRef, useMemo } from 'react';
import { diffHtml } from '@diff-text/core';
import { countHtmlChanges } from '../model';
import type { DiffHtmlOptions, DiffNavigation } from '../model';
import { useStableOptions } from '../useIdPrefix';
import { useNavigation } from '../useNavigation';
import { containerClass, type BaseDiffProps } from './types';

export interface DiffHtmlProps extends BaseDiffProps<DiffHtmlOptions> {
  /**
   * Number between 0 and 1. When set and the text similarity falls below it,
   * the diff renders as a full replacement (old removed, new added).
   * Default: `null` (disabled).
   */
  similarityThreshold?: number | null;
  /**
   * Strip inline formatting tags (`<strong>`, `<em>`, `<b>`, `<i>`, `<u>`,
   * `<s>`, `<mark>`, `<sub>`, `<sup>`) before diffing. Default: `true`.
   */
  ignoreFormattingTags?: boolean;
}

const DEFAULT_OPTIONS: DiffHtmlOptions = {};

/**
 * HTML diff. Output is injected with `dangerouslySetInnerHTML` (the React
 * equivalent of Vue's `v-html`), so `oldText` and `newText` must be trusted
 * or sanitized by the caller before they are passed in.
 */
const DiffHtml = forwardRef<DiffNavigation, DiffHtmlProps>(function DiffHtml(
  { oldText, newText, options = DEFAULT_OPTIONS, similarityThreshold = null, ignoreFormattingTags = true, className, ...rest },
  ref,
) {
  const [stableOptions, optionsKey] = useStableOptions(options);
  const result = useMemo(
    () => diffHtml(oldText, newText, { ...stableOptions, similarityThreshold, ignoreFormattingTags }),
    [oldText, newText, stableOptions, similarityThreshold, ignoreFormattingTags],
  );
  const rootRef = useNavigation(ref, countHtmlChanges(result.html), [
    oldText,
    newText,
    optionsKey,
    similarityThreshold,
    ignoreFormattingTags,
  ]);

  return (
    <div
      {...rest}
      ref={rootRef}
      className={containerClass('text-diff text-diff-html', className)}
      dangerouslySetInnerHTML={{ __html: result.html }}
    />
  );
});

export default DiffHtml;

// packages/vue/src/components/DiffHtml.vue
<template>
  <div
    ref="root"
    class="text-diff text-diff-html"
    v-html="result.html"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { PropType } from 'vue';
import { diffHtml } from '@diff-text/core';
import { countHtmlChanges, fromKey, stableKey } from '../model';
import type { DiffHtmlOptions } from '../model';
import { useNavigation } from '../useNavigation';

const props = defineProps({
  oldText: {
    type: String,
    required: true,
  },
  newText: {
    type: String,
    required: true,
  },
  /** Engine options: orphanMatchThreshold (default 0.3), ignoreCase, maxEditLength. */
  options: {
    type: Object as PropType<DiffHtmlOptions>,
    default: () => ({}),
  },
  /** 0..1. Below this similarity the diff renders as a full replacement. null disables it. */
  similarityThreshold: {
    type: Number as PropType<number | null>,
    default: null,
  },
  /** Strip inline formatting tags (strong, em, b, i, u, s, mark, sub, sup) before diffing. */
  ignoreFormattingTags: {
    type: Boolean,
    default: true,
  },
});

const optionsKey = computed(() => stableKey(props.options));

// Inputs are rendered as raw HTML (v-html): callers must sanitize untrusted input.
const result = computed(() =>
  diffHtml(props.oldText, props.newText, {
    ...fromKey<DiffHtmlOptions>(optionsKey.value),
    similarityThreshold: props.similarityThreshold,
    ignoreFormattingTags: props.ignoreFormattingTags,
  }),
);

const { root, exposed } = useNavigation(
  computed(() => countHtmlChanges(result.value.html)),
  [() => props.oldText, () => props.newText, optionsKey, () => props.similarityThreshold, () => props.ignoreFormattingTags],
);

defineExpose(exposed);
</script>
